name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: bazhenov/action-avr-make@v1.0
    - uses: actions/upload-artifact@v1
      with:
        name: main.bin
        path: main.bin
    - uses: actions/upload-artifact@v1
      with:
        name: main.hex
        path: main.hex
